In [1]:
using Symbolics
#import Pkg; Pkg.add("Tullio")

In [2]:
include("../src/batchSymbolics.jl")

integrateTaylorPolynomials (generic function with 1 method)

In [3]:
# in fact inverse of symbolic matrix is suuuuper costly


In [5]:
@variables dx
matrixA=[1 -dx dx^2//2; 1 0 0 ; 1 dx dx^2//2]
inv(matrixA)

3×3 Matrix{Num}:
            0            1            0
 (-1//2) / dx            0  (1//2) / dx
   1 / (dx^2)  -2 / (dx^2)   1 / (dx^2)

In [6]:
matrixA=[1 -2*dx 4*dx^2//2; 1 -dx dx^2//2 ; 1 0 0]
inv(matrixA)

3×3 Matrix{Num}:
           0             0            1
 (1//2) / dx  (-2//1) / dx  (3//2) / dx
  1 / (dx^2)   -2 / (dx^2)   1 / (dx^2)

In [7]:
matrixA=[ 1 0 0;  1 dx dx^2//2  ;1 2*dx 4*dx^2//2 ]
inv(matrixA)

3×3 Matrix{Num}:
            1            0             0
 (-3//2) / dx  (2//1) / dx  (-1//2) / dx
   1 / (dx^2)  -2 / (dx^2)    1 / (dx^2)

In [10]:
a=rand(500,500)

500×500 Matrix{Float64}:
 0.733623  0.678965   0.292076   0.276631   …  0.297259   0.211224  0.668627
 0.196414  0.140997   0.562846   0.209272      0.0179697  0.281621  0.933231
 0.246059  0.770486   0.496071   0.153217      0.117414   0.342212  0.374992
 0.665363  0.0559678  0.899487   0.36161       0.297128   0.488577  0.862122
 0.91238   0.70549    0.471176   0.576988      0.818615   0.258128  0.908585
 0.681299  0.603588   0.828282   0.64599    …  0.422534   0.360471  0.856909
 0.4323    0.422696   0.142108   0.365121      0.982311   0.921821  0.623476
 0.942463  0.760295   0.361739   0.315103      0.669026   0.892801  0.399697
 0.186851  0.884662   0.655467   0.699237      0.942236   0.188485  0.677516
 0.96097   0.358283   0.0124161  0.583707      0.865112   0.640058  0.788547
 ⋮                                          ⋱                       
 0.334412  0.49335    0.893722   0.163863      0.534107   0.168082  0.55155
 0.296695  0.932877   0.617829   0.344542      0.471216   0.

In [11]:
inv(a)

500×500 Matrix{Float64}:
  0.0355794     0.0946794    -0.636798    …   0.214171     -0.0545574
 -0.0349989    -0.00708275    0.386632       -0.188979      0.0469537
 -0.045021     -0.129647      0.413555       -0.157529     -0.00236282
 -0.0462048    -0.0334175     0.128376       -0.064966     -0.0950489
 -0.0623531     0.0181754     0.050426       -0.0311631    -0.10561
 -0.00249914    0.0530014     0.296436    …   0.000486943   0.076022
  0.0774606     0.0192975     0.157807       -0.15297       0.0306994
  0.0534137     0.135335     -0.0346152       0.0987333     0.0891986
  0.0317629     0.128907      0.382495       -0.217569      0.050502
 -0.0391707    -0.0567354    -0.771964        0.297596     -0.129959
  ⋮                                       ⋱                
 -0.000886068   0.0180129    -0.123605        0.0642344    -0.0472948
  0.036511      0.000891403   0.184739       -0.159557      0.00481332
 -0.0339296    -0.0346266    -0.500446        0.314069     -0.00478423
 -0.067

In [23]:
using LinearAlgebra

In [27]:
@variables Δx
#matrixA=[1 Δx*2 4*Δx^2//2 8*Δx^3//6 16*Δx^4//24; 1 Δx Δx^2//2 Δx^3//6 Δx^4//24; 1 0 0 0 0; 1 -Δx Δx^2//2 -Δx^3//6 Δx^4//24; 1 -2*Δx 4*Δx^2//2 -8*Δx^3//6 16*Δx^4//24]
#matrixA=[ 1 Δx Δx^2//2 Δx^3//6 Δx^4//24; 1 0 0 0 0; 1 -Δx Δx^2//2 -Δx^3//6 Δx^4//24]
matrixA=[ 1 Δx Δx^2//2 ; 1 0 0 ; 1 -Δx Δx^2//2 ]
#@show transpose(matrixA)*matrixA
#@show (inv(transpose(matrixA)*matrixA))
#Cⁿη=(inv(transpose(matrixA)*matrixA))*transpose(matrixA)

invA=inv(matrixA)
#Cⁿη[1:5,1:3]=invA[1:5,2:4]

3×3 Matrix{Num}:
           0            1             0
 (1//2) / Δx            0  (-1//2) / Δx
  1 / (Δx^2)  -2 / (Δx^2)    1 / (Δx^2)

In [30]:
matrixA*invA

3×3 Matrix{Num}:
 1//1  0//1  0//1
    0     1     0
 0//1  0//1  1//1

In [199]:
# then for higher order, we need to control iteratively

@variables nodeValues[1:3]
biggerA1=[ 1 Δx Δx^2//2 Δx^3//6 ; 1 0 0 0 ; 1 -Δx Δx^2//2 -Δx^3//6 ]
biggerA2=[ 1 Δx Δx^2//2 Δx^3//6 Δx^4//24; 1 0 0 0 0; 1 -Δx Δx^2//2 -Δx^3//6 Δx^4//24]


bigALeft= [1 0 0 0 0;1 Δx Δx^2//2 Δx^3//6 Δx^4//24;  1 2*Δx 4*Δx^2//2 8*Δx^3//6 16*Δx^4//24]

3×5 Matrix{Num}:
 1    0              0              0               0
 1   Δx  (1//2)*(Δx^2)  (1//6)*(Δx^3)  (1//24)*(Δx^4)
 1  2Δx  (2//1)*(Δx^2)  (4//3)*(Δx^3)   (2//3)*(Δx^4)

In [209]:
AA=biggerA2*transpose(biggerA2)

3×3 Matrix{Num}:
   1 + Δx^2 + (1//4)*(Δx^4) + (1//36)*(Δx^6) + (1//576)*(Δx^8)  …  1 - (Δx^2) + (1//4)*(Δx^4) - (1//36)*(Δx^6) + (1//576)*(Δx^8)
                                                             1                                                                 1
 1 - (Δx^2) + (1//4)*(Δx^4) - (1//36)*(Δx^6) + (1//576)*(Δx^8)       1 + Δx^2 + (1//4)*(Δx^4) + (1//36)*(Δx^6) + (1//576)*(Δx^8)

In [ ]:

AALeft=bigALeft*transpose(bigALeft)

3×3 Matrix{Num}:
 1  …                                                             1
 1              1 + 2(Δx^2) + Δx^4 + (2//9)*(Δx^6) + (1//36)*(Δx^8)
 1     1 + 4(Δx^2) + (4//1)*(Δx^4) + (16//9)*(Δx^6) + (4//9)*(Δx^8)

In [ ]:
Ainv=mySimplify(inv(AA))
ALeftinv=(inv(AALeft))

3×3 Matrix{Num}:
 (-((1 + 2(Δx^2) + Δx^4 + (2//9)*(Δx^6) + (1//36)*(Δx^8))^2) + (1 + 4(Δx^2) + (4//1)*(Δx^4) + (16//9)*(Δx^6) + (4//9)*(Δx^8))*(1 + Δx^2 + (1//4)*(Δx^4) + (1//36)*(Δx^6) + (1//576)*(Δx^8))) / (-(Δx^2) - (9//4)*(Δx^4) - (49//36)*(Δx^6) - (25//64)*(Δx^8) - ((1 + 2(Δx^2) + Δx^4 + (2//9)*(Δx^6) + (1//36)*(Δx^8))^2) + (1 + 4(Δx^2) + (4//1)*(Δx^4) + (16//9)*(Δx^6) + (4//9)*(Δx^8))*(1 + Δx^2 + (1//4)*(Δx^4) + (1//36)*(Δx^6) + (1//576)*(Δx^8)))  …  (Δx^2 + (3//4)*(Δx^4) + (7//36)*(Δx^6) + (5//192)*(Δx^8)) / (-(Δx^2) - (9//4)*(Δx^4) - (49//36)*(Δx^6) - (25//64)*(Δx^8) - ((1 + 2(Δx^2) + Δx^4 + (2//9)*(Δx^6) + (1//36)*(Δx^8))^2) + (1 + 4(Δx^2) + (4//1)*(Δx^4) + (16//9)*(Δx^6) + (4//9)*(Δx^8))*(1 + Δx^2 + (1//4)*(Δx^4) + (1//36)*(Δx^6) + (1//576)*(Δx^8)))
                                                                                                                                (-2(Δx^2) - (3//1)*(Δx^4) - (14//9)*(Δx^6) - (5//12)*(Δx^8)) / (-(Δx^2) - (9//4)*(Δx^4) - (49//36)*(Δx

In [242]:

theMatrix=mySimplify(transpose(biggerA2)*Ainv)

5×3 Matrix{Num}:
                                           0  …                                            0
   1 / (288((1//144)*Δx + (1//5184)*(Δx^5)))      1 / (288(-(1//144)*Δx - (1//5184)*(Δx^5)))
 1 / (36((1//36)*(Δx^2) + (1//5184)*(Δx^6)))     1 / (36((1//36)*(Δx^2) + (1//5184)*(Δx^6)))
    Δx / (1728((1//144) + (1//5184)*(Δx^4)))       Δx / (1728(-(1//144) - (1//5184)*(Δx^4)))
       1 / (432((1//36) + (1//5184)*(Δx^4)))           1 / (432((1//36) + (1//5184)*(Δx^4)))

In [216]:
theMatrix=mySimplify(transpose(biggerA2)*Ainv)
theMatrixLeft=transpose(bigALeft)*ALeftinv
Symbolics.simplify(Symbolics.expand(theMatrixLeft))

5×3 Matrix{Num}:
 (-((1 + 2(Δx^2) + Δx^4 + (2//9)*(Δx^6) + (1//36)*(Δx^8))^2) + (1 + 4(Δx^2) + (4//1)*(Δx^4) + (16//9)*(Δx^6) + (4//9)*(Δx^8))*(1 + Δx^2 + (1//4)*(Δx^4) + (1//36)*(Δx^6) + (1//576)*(Δx^8))) / (-(Δx^2) - (9//4)*(Δx^4) - (49//36)*(Δx^6) - (25//64)*(Δx^8) - ((1 + 2(Δx^2) + Δx^4 + (2//9)*(Δx^6) + (1//36)*(Δx^8))^2) + (1 + 4(Δx^2) + (4//1)*(Δx^4) + (16//9)*(Δx^6) + (4//9)*(Δx^8))*(1 + Δx^2 + (1//4)*(Δx^4) + (1//36)*(Δx^6) + (1//576)*(Δx^8))) + (Δx^2 + (3//4)*(Δx^4) + (7//36)*(Δx^6) + (5//192)*(Δx^8)) / (-(Δx^2) - (9//4)*(Δx^4) - (49//36)*(Δx^6) - (25//64)*(Δx^8) - ((1 + 2(Δx^2) + Δx^4 + (2//9)*(Δx^6) + (1//36)*(Δx^8))^2) + (1 + 4(Δx^2) + (4//1)*(Δx^4) + (16//9)*(Δx^6) + (4//9)*(Δx^8))*(1 + Δx^2 + (1//4)*(Δx^4) + (1//36)*(Δx^6) + (1//576)*(Δx^8))) + (-2(Δx^2) - (3//1)*(Δx^4) - (14//9)*(Δx^6) - (5//12)*(Δx^8)) / (-(Δx^2) - (9//4)*(Δx^4) - (49//36)*(Δx^6) - (25//64)*(Δx^8) - ((1 + 2(Δx^2) + Δx^4 + (2//9)*(Δx^6) + (1//36)*(Δx^8))^2) + (1 + 4(Δx^2) + (4//1)*(Δx^4) + (16//9)*(Δx^6

In [223]:
denom=mySimplify(-Δx^2-9/4*Δx^4-49/36*Δx^6-25//64*Δx^8 -(1+2*Δx^2 +Δx^4+2/9*Δx^6+1//36*Δx^8)*(1+2*Δx^2 +Δx^4+2/9*Δx^6+1/36*Δx^8) + (1+4*Δx^2+4*Δx^4+16/9*Δx^6+4/9*Δx^8)*(1+Δx^2+1/4*Δx^4+1//36*Δx^6+1//576*Δx^8))

Δx^6 + Δx^8 + 0.45138888888888884(Δx^10) + 0.0625(Δx^12) + 0.0030864197530864196(Δx^14)

In [235]:
simplify(theMatrixLeft[1,1])

1

In [229]:
simplify(theMatrixLeft[1,2]*denom)

0

In [230]:
simplify(theMatrixLeft[1,3]*denom)

0

In [236]:
simplify(theMatrixLeft[2,1])

(-1.5000000000000202 - 1.1666666666666659(Δx^2) - 0.36458333333333337(Δx^4)) / (Δx + 1.0000000000000002(Δx^3) + 0.45138888888888884(Δx^5) + 0.0625(Δx^7) + 0.0030864197530864196(Δx^9))

In [237]:
simplify(theMatrixLeft[2,2])

(1.999999999999991 + 1.333333333333333(Δx^2) + 0.3888888888888889(Δx^4)) / (Δx + 1.0000000000000002(Δx^3) + 0.45138888888888884(Δx^5) + 0.0625(Δx^7) + 0.0030864197530864196(Δx^9))

In [238]:
simplify(theMatrixLeft[2,3])

(-0.5 - 0.16666666666666669(Δx^2) - 0.024305555555555556(Δx^4)) / (Δx + 1.0000000000000002(Δx^3) + 0.45138888888888884(Δx^5) + 0.0625(Δx^7) + 0.0030864197530864196(Δx^9))

In [239]:
simplify(theMatrixLeft[3,1])

(1.0000000000000135 - 0.388888888888889(Δx^4) - 0.15625(Δx^6)) / (Δx^2 + 1.0000000000000002(Δx^4) + 0.45138888888888884(Δx^6) + 0.0625(Δx^8) + 0.0030864197530864196(Δx^10))

In [240]:
simplify(theMatrixLeft[3,2])

(-2.0 + 0.44444444444444453(Δx^4) + 0.16666666666666666(Δx^6)) / (Δx^2 + 1.0000000000000002(Δx^4) + 0.45138888888888884(Δx^6) + 0.0625(Δx^8) + 0.0030864197530864196(Δx^10))

In [ ]:
simplify(theMatrixLeft[1,1]*denom)

In [205]:
@variables u₋ u₀ u₊
@variables u₊₊
u_deriv=theMatrix*[u₋; u₀ ; u₊]
u_deriv_Left=theMatrixLeft*[u₀;u₊; u₊₊] 

5-element Vector{Num}:
 u₀*((-((1 + 2(Δx^2) + Δx^4 + (2//9)*(Δx^6) + (1//36)*(Δx^8))^2) + (1 + 4(Δx^2) + (4//1)*(Δx^4) + (16//9)*(Δx^6) + (4//9)*(Δx^8))*(1 + Δx^2 + (1//4)*(Δx^4) + (1//36)*(Δx^6) + (1//576)*(Δx^8))) / (-(Δx^2) - (9//4)*(Δx^4) - (49//36)*(Δx^6) - (25//64)*(Δx^8) - ((1 + 2(Δx^2) + Δx^4 + (2//9)*(Δx^6) + (1//36)*(Δx^8))^2) + (1 + 4(Δx^2) + (4//1)*(Δx^4) + (16//9)*(Δx^6) + (4//9)*(Δx^8))*(1 + Δx^2 + (1//4)*(Δx^4) + (1//36)*(Δx^6) + (1//576)*(Δx^8))) + (Δx^2 + (3//4)*(Δx^4) + (7//36)*(Δx^6) + (5//192)*(Δx^8)) / (-(Δx^2) - (9//4)*(Δx^4) - (49//36)*(Δx^6) - (25//64)*(Δx^8) - ((1 + 2(Δx^2) + Δx^4 + (2//9)*(Δx^6) + (1//36)*(Δx^8))^2) + (1 + 4(Δx^2) + (4//1)*(Δx^4) + (16//9)*(Δx^6) + (4//9)*(Δx^8))*(1 + Δx^2 + (1//4)*(Δx^4) + (1//36)*(Δx^6) + (1//576)*(Δx^8))) + (-2(Δx^2) - (3//1)*(Δx^4) - (14//9)*(Δx^6) - (5//12)*(Δx^8)) / (-(Δx^2) - (9//4)*(Δx^4) - (49//36)*(Δx^6) - (25//64)*(Δx^8) - ((1 + 2(Δx^2) + Δx^4 + (2//9)*(Δx^6) + (1//36)*(Δx^8))^2) + (1 + 4(Δx^2) + (4//1)*(Δx^4) + (16

In [207]:
mySimplify(u_deriv_Left[1]+Δx*u_deriv_Left[2]+Δx^2/2*u_deriv_Left[3]+Δx^3/6*u_deriv_Left[4]+Δx^4/24*u_deriv_Left[5])

OverflowError: OverflowError: 429981696 * 34828517376 overflowed for type Int64

In [115]:
mySimplify(u_deriv[1]+Δx*u_deriv[2]+Δx^2/2*u_deriv[3]+Δx^3/6*u_deriv[4]+Δx^4/24*u_deriv[5])

u₋

In [116]:
Δx^4/24*u_deriv[5]

(1//24)*(u₋ / (432((1//36) + (1//5184)*(Δx^4))) + ((1//216)*u₀) / (-(1//36) - (1//5184)*(Δx^4)) + u₊ / (432((1//36) + (1//5184)*(Δx^4))))*(Δx^4)

In [117]:
u_deriv[2]

u₋ / (288((1//144)*Δx + (1//5184)*(Δx^5))) + u₊ / (288(-(1//144)*Δx - (1//5184)*(Δx^5)))

In [182]:
Cⁿη=[0 1 0; 1/(2*Δx + Δx^5/18) 0 -1/(2*Δx + Δx^5/18 ); 1/(Δx^2+Δx^6/ 144) -2/(Δx^2+Δx^6 / 144)  1/(Δx^2+Δx^6/ 144); 1/(12/Δx + Δx^3/3)  0  -1/(12/Δx + Δx^3/3);  1/(12+Δx^4/12) -2/(12+Δx^4/12) 1/(12+Δx^4/12)]

5×3 Matrix{Num}:
                             0  …                               0
    1 / (2Δx + (1//18)*(Δx^5))        -1 / (2Δx + (1//18)*(Δx^5))
  1 / (Δx^2 + (1//144)*(Δx^6))       1 / (Δx^2 + (1//144)*(Δx^6))
 1 / (12 / Δx + (1//3)*(Δx^3))     -1 / (12 / Δx + (1//3)*(Δx^3))
     1 / (12 + (1//12)*(Δx^4))          1 / (12 + (1//12)*(Δx^4))

In [128]:
u_deriv=Cⁿη*[u₋; u₀ ; u₊]
mySimplify(u_deriv[1]+Δx*u_deriv[2]+Δx^2/2*u_deriv[3]+Δx^3/6*u_deriv[4]+Δx^4/24*u_deriv[5])

u₋

In [119]:
CⁿηSimple=[0 1 0; 1/(2*Δx) 0 -1/(2*Δx  ); 1/(Δx^2) -2/(Δx^2)  1/(Δx^2); 1/(12/Δx )  0  -1/(12/Δx );  1//(12) -2//(12) 1//(12)]

5×3 Matrix{Num}:
          0            1           0
  1 / (2Δx)            0  -1 / (2Δx)
 1 / (Δx^2)  -2 / (Δx^2)  1 / (Δx^2)
    Δx / 12            0  (-Δx) / 12
      1//12        -1//6       1//12

In [120]:
u_derivSimple=CⁿηSimple*[u₋; u₀ ; u₊]

5-element Vector{Num}:
                                          u₀
                  (-u₊) / (2Δx) + u₋ / (2Δx)
 u₋ / (Δx^2) + u₊ / (Δx^2) + (-2u₀) / (Δx^2)
                (-u₊*Δx) / 12 + (u₋*Δx) / 12
        -(1//6)*u₀ + (1//12)*u₊ + (1//12)*u₋

In [121]:
mySimplify(u_derivSimple[1]+Δx*u_derivSimple[2]+Δx^2/2*u_derivSimple[3]+Δx^3/6*u_derivSimple[4]+Δx^4/24*u_derivSimple[5])

u₋ - (1//144)*u₀*(Δx^4) - (1//96)*u₊*(Δx^4) + (5//288)*u₋*(Δx^4)

In [130]:
Cⁿη=CⁿηSimple

5×3 Matrix{Num}:
          0            1           0
  1 / (2Δx)            0  -1 / (2Δx)
 1 / (Δx^2)  -2 / (Δx^2)  1 / (Δx^2)
    Δx / 12            0  (-Δx) / 12
      1//12        -1//6       1//12

In [185]:
Cⁿη[5,2] #  the order is ( n, η ) but n from 0 to 2 and η from -1 to 1 here

-2 / (12 + (1//12)*(Δx^4))

In [183]:
lᶜ = 0:2 # l prime
n_minus_l=0:2
l = 0:2

0:2

In [248]:
# computing eq. 58 for \alpha = constant

@variables Δx
@variables α⁰[1:3]
@variables u[1:3]

lᶜmax = 0
n_minus_l_max = 2

objectFunction = 0
nᶜ = 1

for ηᶜ in -1:1:1 # the neighbouring points
    if ηᶜ == -1
        uuu = u₋
    elseif ηᶜ == 0
        uuu = u₀
    elseif ηᶜ == 1
        uuu = u₊
    end

    for lᶜ in 0:lᶜmax # the degree of derivatives of material variables to be considered
        for n_minus_l in 0:n_minus_l_max
            #for l in 0:2

            for ηmaterial in -1:1:1
            l =1
                n = n_minus_l + l
                power = lᶜ+n_minus_l+1
                denominator = (power+1)*power*factorial(lᶜ)*factorial(n_minus_l)
                integralOfWandTaylor=mySimplify(Δx^power/ denominator-((-Δx)^power)/denominator)
                if n <=4
                    objectFunction+=α⁰[ηᶜ+2]*Cⁿη[n+1,ηᶜ+2]*Cⁿη[nᶜ+1,ηmaterial+2]* uuu*integralOfWandTaylor
                end 
            #end
            end
        end
    end
end


objectFunction

(u₋*Δx*α⁰[1]) / ((2Δx + (1//18)*(Δx^5))^2) + (u₋*(Δx^3)*α⁰[1]) / (12(12 / Δx + (1//3)*(Δx^3))*(2Δx + (1//18)*(Δx^5))) + (-u₋*(Δx^3)*α⁰[1]) / (12(12 / Δx + (1//3)*(Δx^3))*(2Δx + (1//18)*(Δx^5))) + (-u₊*(Δx^3)*α⁰[3]) / (12(12 / Δx + (1//3)*(Δx^3))*(2Δx + (1//18)*(Δx^5))) + (u₊*(Δx^3)*α⁰[3]) / (12(12 / Δx + (1//3)*(Δx^3))*(2Δx + (1//18)*(Δx^5))) + (u₊*Δx*α⁰[3]) / ((2Δx + (1//18)*(Δx^5))^2) + (-u₊*Δx*α⁰[3]) / ((2Δx + (1//18)*(Δx^5))^2) + (-u₋*Δx*α⁰[1]) / ((2Δx + (1//18)*(Δx^5))^2)

In [ ]:
# computing eq. 56 for \alpha that changes

@variables Δx
@variables α[1:3,1:3] # l, \eta order
@variables u[1:3]

lᶜmax = 2
n_minus_l_max = 2

objectFunction = 0

for ηᶜ in -1:1:1 # the neighbouring points (u)
    if ηᶜ == -1
        uuu = u₋
    elseif ηᶜ == 0
        uuu = u₀
    elseif ηᶜ == 1
        uuu = u₊
    end

    for η in -1:1:1 # the neighbouring points (α)

        for lᶜ in 0:lᶜmax # the degree of derivatives of material variables to be considered
            for n_minus_l in 0:n_minus_l_max
                #for l in 0:2

                l =0

                

                    n = n_minus_l + l
                    power = lᶜ+n_minus_l+1
                    denominator = (power+1)*power*factorial(lᶜ)*factorial(n_minus_l)
                    integralOfWandTaylor=mySimplify(Δx^power/ denominator-((-Δx)^power)/denominator)
                    if n <=4 && lᶜ<=4
                        objectFunction+=α[l+1,ηᶜ+2]*Cⁿη[lᶜ+1,η+2]*Cⁿη[n+1,ηᶜ+2]*uuu*integralOfWandTaylor
                    end 
                #end
            end
        end
    end
end


objectFunction

((1//30)*u₊*(Δx^5)*α[1, 3]) / ((Δx^2 + (1//144)*(Δx^6))^2) + ((-1//30)*u₊*(Δx^5)*α[1, 3]) / ((Δx^2 + (1//144)*(Δx^6))^2) + ((-1//30)*u₋*(Δx^5)*α[1, 1]) / ((Δx^2 + (1//144)*(Δx^6))^2) + ((-1//6)*u₋*(Δx^3)*α[1, 1]) / ((2Δx + (1//18)*(Δx^5))^2) + ((1//6)*u₊*(Δx^3)*α[1, 3]) / ((2Δx + (1//18)*(Δx^5))^2) + ((1//6)*u₋*(Δx^3)*α[1, 1]) / ((2Δx + (1//18)*(Δx^5))^2) + ((1//12)*u₋*(Δx^3)*α[1, 1]) / (Δx^2 + (1//144)*(Δx^6)) + ((1//30)*u₋*(Δx^5)*α[1, 1]) / ((Δx^2 + (1//144)*(Δx^6))^2) + ((-1//6)*u₊*(Δx^3)*α[1, 3]) / ((2Δx + (1//18)*(Δx^5))^2) + ((1//15)*u₀*(Δx^5)*α[1, 2]) / ((Δx^2 + (1//144)*(Δx^6))^2) + ((-1//3)*u₀*(Δx^3)*α[1, 2]) / (Δx^2 + (1//144)*(Δx^6)) + ((-1//15)*u₀*(Δx^5)*α[1, 2]) / ((Δx^2 + (1//144)*(Δx^6))^2) + ((1//6)*u₀*(Δx^3)*α[1, 2]) / (Δx^2 + (1//144)*(Δx^6)) + ((1//12)*u₊*(Δx^3)*α[1, 3]) / (Δx^2 + (1//144)*(Δx^6)) + u₀*Δx*α[1, 2]

In [193]:
display(objectFunction)

((1//15)*u₀*(Δx^5)*α[2, 1]) / ((Δx^2 + (1//144)*(Δx^6))^2) + ((1//6)*u₊*(Δx^3)*α[3, 1]) / ((2Δx + (1//18)*(Δx^5))^2) + ((-1//6)*u₀*(Δx^3)*α[2, 3]) / (12 + (1//12)*(Δx^4)) + (u₋*Δx*α[1, 3]) / (Δx^2 + (1//144)*(Δx^6)) + ((-1//3)*u₀*(Δx^3)*α[2, 3]) / ((Δx^2 + (1//144)*(Δx^6))^2) + ((1//12)*u₋*(Δx^3)*α[1, 3]) / (12 + (1//12)*(Δx^4)) + ((-1//6)*u₊*(Δx^3)*α[3, 1]) / ((2Δx + (1//18)*(Δx^5))^2) + ((-1//6)*u₋*(Δx^3)*α[1, 3]) / ((Δx^2 + (1//144)*(Δx^6))^2) + ((-1//6)*u₊*(Δx^3)*α[3, 3]) / ((Δx^2 + (1//144)*(Δx^6))^2) + ((-1//30)*u₋*(Δx^5)*α[1, 1]) / ((Δx^2 + (1//144)*(Δx^6))^2) + ((-1//6)*u₋*(Δx^3)*α[1, 1]) / ((2Δx + (1//18)*(Δx^5))^2) + (u₊*Δx*α[3, 3]) / (Δx^2 + (1//144)*(Δx^6)) + (-u₀*(Δx^3)*α[2, 2]) / (3(2Δx + (1//18)*(Δx^5))*(Δx^2 + (1//144)*(Δx^6))) + (-u₀*(Δx^5)*α[2, 3]) / (15(12 + (1//12)*(Δx^4))*(Δx^2 + (1//144)*(Δx^6))) + (u₀*(Δx^5)*α[2, 3]) / (15(12 + (1//12)*(Δx^4))*(Δx^2 + (1//144)*(Δx^6))) + (u₋*(Δx^3)*α[1, 2]) / (6(2Δx + (1//18)*(Δx^5))*(Δx^2 + (1//144)*(Δx^6))) + (u₋*(Δx^3)*α[1, 3]

In [171]:
D₋ =  Differential(u₋)
expand_derivatives(Differential(u₋)(objectFunction))

(1//3)*α⁰[2] + 0.16666666666666666Δx*α⁰[1] + 0.027777777777777776(Δx^3)*α⁰[3]

In [125]:

# computing eq. 58

@variables Δx
@variables α[1:3,1:3] # in the order of ( η, l )
@variables α⁰[1:3]
@variables Aννᶜ[1:3]
@variables u[1:3]
ν =2



a=0



for νᶜ in -1:1:1
    for η in -1:1:1 # from -1 to 0 normally
        for l_tmp in l
            for lᶜ_tmp in lᶜ
                for n_minus_l_tmp in n_minus_l
                    n=l_tmp+n_minus_l_tmp
                    power=lᶜ_tmp + n_minus_l_tmp + 1
                    denominator=(power+1)*power*factorial(n_minus_l_tmp)*factorial(l_tmp)
                    #@show l_tmp, lᶜ_tmp, n_minus_l_tmp
                    #print(mySimplify(Δx^power/ denominator+((-Δx)^power)/denominator))
                    #print('\n')
                    integralOfWandTaylor=mySimplify(Δx^power/ denominator+((-Δx)^power)/denominator)
                    if n+1 <=5
                        #tmp = mySimplify(Cⁿη[lᶜ_tmp+1,η+2]*Cⁿη[n+1,νᶜ+2]* α[η+2,l_tmp+1] * integralOfWandTaylor)
                        tmp=mySimplify(Cⁿη[lᶜ_tmp+1,η+2]*Cⁿη[n+1,νᶜ+2]* α⁰[l_tmp+1] * integralOfWandTaylor)
                        #@show Aννᶜ[νᶜ+2]
                        a=a+tmp*u[νᶜ+2]
                        #Aννᶜ[νᶜ+2]+=  Cⁿη[lᶜ_tmp+1,η+2]*Cⁿη[n+1,νᶜ+2]* α[η+2,l_tmp+1] * integralOfWandTaylor
                    end
                end
            end
        end
    end
end
@show mySimplify(a)


mySimplify(a) = (1//72)*((24//1)*u[1]*α⁰[2] - (48//1)*u[2]*α⁰[2] + (24//1)*u[3]*α⁰[2] + (12//1)*u[1]*Δx*α⁰[1] - (12//1)*u[3]*Δx*α⁰[1] + u[1]*(Δx^3)*α⁰[3] - u[3]*(Δx^3)*α⁰[3])


(1//72)*((24//1)*u[1]*α⁰[2] - (48//1)*u[2]*α⁰[2] + (24//1)*u[3]*α⁰[2] + (12//1)*u[1]*Δx*α⁰[1] - (12//1)*u[3]*Δx*α⁰[1] + u[1]*(Δx^3)*α⁰[3] - u[3]*(Δx^3)*α⁰[3])

In [12]:
@variables t,x,y,z
L=[3 1 1 1]
@variables whatsoever[1:L[1],1:L[2],1:L[3],1:L[4]]
@variables ∂whatsoever[1:L[1],1:L[2],1:L[3],1:L[4]]
@variables Δt[1:L[1]] Δx[1:L[2]] Δy[1:L[3]] Δz[1:L[4]]


4-element Vector{Symbolics.Arr{Num, 1}}:
 Δt[1:3]
 Δx[1:1]
 Δy[1:1]
 Δz[1:1]

In [13]:

eqns=[]
for jz in 1:L[4]
    for jy in 1:L[3]
        for jx in 1:L[2]
            for jt in 1:L[1]
                t=Δt[jt]
                x=Δx[jx]
                y=Δy[jy]
                z=Δz[jz]
                eqns=push!(eqns,whatsoever[jt,jx,jy,jz]~sum(sum(sum(sum(∂whatsoever[it,ix,iy,iz]*t^(it-1)*x^(ix-1)*y^(iy-1)*z^(iz-1)
    // factorial(BigInt(it-1)) // factorial(BigInt(ix-1)) // factorial(BigInt(iy-1)) // factorial(BigInt(iz-1)) 
    for it in 1:L[1]; init=0) for ix in 1:L[2]; init=0) for iy in 1:L[3]; init=0) for iz in 1:L[4]; init=0))
            end
        end
    end
end



In [14]:
eqns

3-element Vector{Any}:
 whatsoever[1, 1, 1, 1] ~ ∂whatsoever[1, 1, 1, 1] + Δt[1]*∂whatsoever[2, 1, 1, 1] + (1//2)*(Δt[1]^2)*∂whatsoever[3, 1, 1, 1]
 whatsoever[2, 1, 1, 1] ~ ∂whatsoever[1, 1, 1, 1] + Δt[2]*∂whatsoever[2, 1, 1, 1] + (1//2)*(Δt[2]^2)*∂whatsoever[3, 1, 1, 1]
 whatsoever[3, 1, 1, 1] ~ ∂whatsoever[1, 1, 1, 1] + Δt[3]*∂whatsoever[2, 1, 1, 1] + (1//2)*(Δt[3]^2)*∂whatsoever[3, 1, 1, 1]

In [15]:
tmp=mySolvefor(eqns,∂whatsoever)

3-element Vector{SymbolicUtils.BasicSymbolic{Real}}:
 (-(1//4)*whatsoever[1, 1, 1, 1]*(Δt[2]^2)*Δt[3] + (1//4)*whatsoever[1, 1, 1, 1]*Δt[2]*(Δt[3]^2) + (1//4)*whatsoever[2, 1, 1, 1]*(Δt[1]^2)*Δt[3] - (1//4)*whatsoever[2, 1, 1, 1]*Δt[1]*(Δt[3]^2) - (1//4)*whatsoever[3, 1, 1, 1]*(Δt[1]^2)*Δt[2] + (1//4)*whatsoever[3, 1, 1, 1]*Δt[1]*(Δt[2]^2)) / ((1//2)*(-Δt[1] + Δt[2])*((1//2)*Δt[1]*Δt[2] - (1//2)*Δt[1]*Δt[3] - (1//2)*Δt[2]*Δt[3] + (1//2)*(Δt[3]^2)))
 ((1//2)*whatsoever[1, 1, 1, 1]*(Δt[2]^2) - (1//2)*whatsoever[1, 1, 1, 1]*(Δt[3]^2) - (1//2)*whatsoever[2, 1, 1, 1]*(Δt[1]^2) + (1//2)*whatsoever[2, 1, 1, 1]*(Δt[3]^2) + (1//2)*whatsoever[3, 1, 1, 1]*(Δt[1]^2) - (1//2)*whatsoever[3, 1, 1, 1]*(Δt[2]^2)) / ((-Δt[1] + Δt[2])*((1//2)*Δt[1]*Δt[2] - (1//2)*Δt[1]*Δt[3] - (1//2)*Δt[2]*Δt[3] + (1//2)*(Δt[3]^2)))
 (-whatsoever[1, 1, 1, 1]*Δt[2] + whatsoever[1, 1, 1, 1]*Δt[3] + whatsoever[2, 1, 1, 1]*Δt[1] - whatsoever[2, 1, 1, 1]*Δt[3] - whatsoever[3, 1, 1, 1]*Δt[1] + whatsoever[3, 1, 1, 1]*Δt[2]) / (

In [16]:
new∂whatsoever=reshape(tmp,(L[1],L[2],L[3],L[4]))

3×1×1×1 Array{SymbolicUtils.BasicSymbolic{Real}, 4}:
[:, :, 1, 1] =
 (-(1//4)*whatsoever[1, 1, 1, 1]*(Δt[2]^2)*Δt[3] + (1//4)*whatsoever[1, 1, 1, 1]*Δt[2]*(Δt[3]^2) + (1//4)*whatsoever[2, 1, 1, 1]*(Δt[1]^2)*Δt[3] - (1//4)*whatsoever[2, 1, 1, 1]*Δt[1]*(Δt[3]^2) - (1//4)*whatsoever[3, 1, 1, 1]*(Δt[1]^2)*Δt[2] + (1//4)*whatsoever[3, 1, 1, 1]*Δt[1]*(Δt[2]^2)) / ((1//2)*(-Δt[1] + Δt[2])*((1//2)*Δt[1]*Δt[2] - (1//2)*Δt[1]*Δt[3] - (1//2)*Δt[2]*Δt[3] + (1//2)*(Δt[3]^2)))
 ((1//2)*whatsoever[1, 1, 1, 1]*(Δt[2]^2) - (1//2)*whatsoever[1, 1, 1, 1]*(Δt[3]^2) - (1//2)*whatsoever[2, 1, 1, 1]*(Δt[1]^2) + (1//2)*whatsoever[2, 1, 1, 1]*(Δt[3]^2) + (1//2)*whatsoever[3, 1, 1, 1]*(Δt[1]^2) - (1//2)*whatsoever[3, 1, 1, 1]*(Δt[2]^2)) / ((-Δt[1] + Δt[2])*((1//2)*Δt[1]*Δt[2] - (1//2)*Δt[1]*Δt[3] - (1//2)*Δt[2]*Δt[3] + (1//2)*(Δt[3]^2)))
 (-whatsoever[1, 1, 1, 1]*Δt[2] + whatsoever[1, 1, 1, 1]*Δt[3] + whatsoever[2, 1, 1, 1]*Δt[1] - whatsoever[2, 1, 1, 1]*Δt[3] - whatsoever[3, 1, 1, 1]*Δt[1] + whatsoever[3, 1, 1

In [ ]:
C=Symbolics.variables(:C,1:4,1:4)

10×10 Matrix{Num}:
  C₁ˏ₁   C₁ˏ₂   C₁ˏ₃   C₁ˏ₄   C₁ˏ₅   C₁ˏ₆   C₁ˏ₇   C₁ˏ₈   C₁ˏ₉   C₁ˏ₁₀
  C₂ˏ₁   C₂ˏ₂   C₂ˏ₃   C₂ˏ₄   C₂ˏ₅   C₂ˏ₆   C₂ˏ₇   C₂ˏ₈   C₂ˏ₉   C₂ˏ₁₀
  C₃ˏ₁   C₃ˏ₂   C₃ˏ₃   C₃ˏ₄   C₃ˏ₅   C₃ˏ₆   C₃ˏ₇   C₃ˏ₈   C₃ˏ₉   C₃ˏ₁₀
  C₄ˏ₁   C₄ˏ₂   C₄ˏ₃   C₄ˏ₄   C₄ˏ₅   C₄ˏ₆   C₄ˏ₇   C₄ˏ₈   C₄ˏ₉   C₄ˏ₁₀
  C₅ˏ₁   C₅ˏ₂   C₅ˏ₃   C₅ˏ₄   C₅ˏ₅   C₅ˏ₆   C₅ˏ₇   C₅ˏ₈   C₅ˏ₉   C₅ˏ₁₀
  C₆ˏ₁   C₆ˏ₂   C₆ˏ₃   C₆ˏ₄   C₆ˏ₅   C₆ˏ₆   C₆ˏ₇   C₆ˏ₈   C₆ˏ₉   C₆ˏ₁₀
  C₇ˏ₁   C₇ˏ₂   C₇ˏ₃   C₇ˏ₄   C₇ˏ₅   C₇ˏ₆   C₇ˏ₇   C₇ˏ₈   C₇ˏ₉   C₇ˏ₁₀
  C₈ˏ₁   C₈ˏ₂   C₈ˏ₃   C₈ˏ₄   C₈ˏ₅   C₈ˏ₆   C₈ˏ₇   C₈ˏ₈   C₈ˏ₉   C₈ˏ₁₀
  C₉ˏ₁   C₉ˏ₂   C₉ˏ₃   C₉ˏ₄   C₉ˏ₅   C₉ˏ₆   C₉ˏ₇   C₉ˏ₈   C₉ˏ₉   C₉ˏ₁₀
 C₁₀ˏ₁  C₁₀ˏ₂  C₁₀ˏ₃  C₁₀ˏ₄  C₁₀ˏ₅  C₁₀ˏ₆  C₁₀ˏ₇  C₁₀ˏ₈  C₁₀ˏ₉  C₁₀ˏ₁₀